# Generated by Django 6.0 on 2025-12-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('imagen', models.ImageField(upload_to='cupones_img/')),
                ('fecha_expiracion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
                ('fue_canjeado', models.BooleanField(default=False)),
            ],
        ),
    ]
